import { useState } from 'react'
import { Activity, CircleHelp, ShieldPlus, Siren, X } from 'lucide-react'
import AdminVerification from './components/AdminVerification'
import EmergencyFlow from './components/EmergencyFlow'
import ResponderDashboard from './components/ResponderDashboard'
import ResponderRegistration from './components/ResponderRegistration'
import './App.css'

function App() {
  const [view, setView] = useState('home')
  const [responder, setResponder] = useState(null)
  if (view === 'emergency') return <PageShell onHome={() => setView('home')} onResponder={() => setView('responder')} onAdmin={() => setView('admin')}><EmergencyFlow onBack={() => setView('home')} /></PageShell>
  if (view === 'register') return <PageShell onHome={() => setView('home')} onResponder={() => setView('responder')} onAdmin={() => setView('admin')}><ResponderRegistration onRegistered={setResponder} /></PageShell>
  if (view === 'responder') return <PageShell onHome={() => setView('home')} onResponder={() => setView('responder')} onAdmin={() => setView('admin')}><ResponderDashboard responder={responder} /></PageShell>
  if (view === 'admin') return <PageShell onHome={() => setView('home')} onResponder={() => setView('responder')} onAdmin={() => setView('admin')}><AdminVerification /></PageShell>
  return <PageShell onHome={() => setView('home')} onResponder={() => setView('responder')} onAdmin={() => setView('admin')}><section className="home-hero"><div className="home-hero-inner"><p className="home-tagline"><span className="tagline-pulse" aria-hidden="true" /><strong>Every minute matters.</strong></p><p className="home-subtitle">Instantly connect people in emergencies with nearby verified responders — before professional help arrives.</p><div className="home-actions"><button className="home-action emergency-action" type="button" onClick={() => { sessionStorage.removeItem('activeEmergencyId'); setView('emergency') }}><span className="action-icon"><Siren className="size-6" /></span><span><strong>Send Emergency Alert</strong><small>Alert nearby verified responders now</small></span></button><button className="home-action responder-action" type="button" onClick={() => setView('register')}><span className="action-icon"><ShieldPlus className="size-6" /></span><span><strong>Register as Responder</strong><small>Join the verified responder network</small></span></button></div><p className="home-note"><span className="note-line" />For life-threatening emergencies, always call&nbsp;<strong>108</strong> first<span className="note-line" /></p></div></section></PageShell>
}

function PageShell({ children, onHome, onResponder, onAdmin }) {
  const [helpOpen, setHelpOpen] = useState(false)
  return <main className="min-h-screen overflow-hidden bg-[#f7f8f6] text-slate-900"><div className="ambient-shape ambient-shape-one" /><div className="ambient-shape ambient-shape-two" /><header className="relative mx-auto flex max-w-6xl items-center justify-between px-6 py-6 lg:px-10"><button className="flex items-center gap-3" type="button" onClick={onHome}><span className="brand-mark"><Activity className="size-5" strokeWidth={2.5} /></span><span className="text-sm font-bold tracking-wide text-slate-950">COMMUNITY RESPONSE</span></button><div className="flex items-center gap-3"><button className="quiet-link hidden sm:block" type="button" onClick={onResponder}>Responder tools</button><button className="quiet-link hidden sm:block" type="button" onClick={onAdmin}>Admin</button><button className="help-button" type="button" aria-label="Get help" aria-haspopup="dialog" aria-expanded={helpOpen} onClick={() => setHelpOpen(true)}><CircleHelp className="size-5" /></button></div></header><section className="relative mx-auto max-w-6xl px-6 pb-16 pt-12 lg:px-10 lg:pb-24 lg:pt-16">{children}</section><footer className="relative border-t border-slate-200/80"><div className="mx-auto flex max-w-6xl flex-col gap-2 px-6 py-6 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between lg:px-10"><span>SIH 2026 MVP</span><span>Prototype workflow for community-assisted response.</span></div></footer>{helpOpen && <div className="help-overlay" role="presentation" onMouseDown={() => setHelpOpen(false)}><section className="help-dialog" role="dialog" aria-modal="true" aria-labelledby="help-title" onMouseDown={(event) => event.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Need help?</p><h2 id="help-title" className="mt-2 text-2xl font-bold text-slate-950">How Community Response works</h2></div><button className="help-close" type="button" aria-label="Close help" onClick={() => setHelpOpen(false)}><X className="size-5" /></button></div><div className="help-callout"><strong>For an immediate emergency, call <a href="tel:108">108</a>.</strong><span>This platform supports the response; it does not replace emergency services.</span></div><div className="help-list"><div><strong>Send an emergency alert</strong><p>Choose the emergency type, take a scene photo, confirm your location, then send the alert to nearby responders.</p></div><div><strong>Become a responder</strong><p>Register with your details and verification document. An admin must approve your registration before you can go online.</p></div><div><strong>Admin review</strong><p>Review a submitted document and choose Verify or Reject. Completed decisions cannot be changed in this prototype.</p></div></div><button className="secondary-button mt-6" type="button" onClick={() => setHelpOpen(false)}>Close help</button></section></div>}</main>
}

export default App
